### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by dantedoyl** [iu5git/Networking#1]
Замечания
--
Варианты ДЗ
--
1.Обмен статусами собеседников через WebSocket
--
> Должна быть предусмотрена гарантированная отправка 

Что это значит?

---

> То есть отображать нужно версии в порядке очередности.

Проще написать, что нужно сообщение выводить в порядке отправки.

---

Добавление к требования к приложению:

4. Если установлено соединение с двумя клиентами с одним идентификатором, то сообщение должно появляться у обоих.

---

Добавлению к порядку показа:

Если это будет веб-приложение, то в браузере нужно показать запрос на изменение протокола, и как там идут сообщения. Показывается легко через инструменты разработчика в Google Chrome.

---

2.Отправка email, телеграм, vk через очередь сообщений
--
Пока не понятно, что именно требуется. Лучше обсудить эту тему.

---

3.Отправка, получение файлов в файловом хранилище
--

В целом, довольно интересное ДЗ. Только не уверен, что среднестатистический студент справится с настройкой docker-compose и nginx. Но можно поэкспериментировать.

---

4.Сервис блокчейна
--

Здесь не подскажу, так как особо не разбираюсь в предметной области)

---

Курсовой проект
--

1. Мне кажется, к 12 неделе лучше прототип, чем полный комплект документов. Можно будет провести смотр и сделать ревью, чтобы к защите у них был хорошо сделанный продукт. А документацию они уже будут писать уже с внесением корректировок.
2. Чем темы отличаются от вариантов? 
3. Думаю на защиту стоит потребовать презентацию. Это неплохая тренировка будет перед защитой диплома.

**Comment by iu5git** [comment]
Внесены корректировки
